#!/usr/bin/env python3
"""Run the ChaOS Meta-Agent review.

This script reads a small, explicit set of repository files, sends the combined
context to the OpenAI Responses API, and saves a Markdown report. It does not
apply any recommended changes.
"""

from __future__ import annotations

import json
import os
import sys
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = ROOT / "docs" / "journal" / "0001-meta-agent-review.md"
CONTEXT_FILES = [
    ROOT / "AGENTS.md",
    ROOT / "README.md",
    ROOT / "docs" / "architecture.md",
    ROOT / "docs" / "architectural-laws.md",
    ROOT / "docs" / "meta-agent.md",
    ROOT / "agents" / "meta-agent" / "prompt.md",
]


def load_dotenv(path: Path) -> None:
    if not path.exists():
        return

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key, value)


def read_context() -> str:
    sections: list[str] = []
    missing: list[str] = []

    for path in CONTEXT_FILES:
        if not path.exists():
            missing.append(str(path.relative_to(ROOT)))
            continue
        relative = path.relative_to(ROOT).as_posix()
        content = path.read_text(encoding="utf-8")
        sections.append(f"## FILE: {relative}\n\n{content.strip()}\n")

    if missing:
        raise FileNotFoundError(
            "Missing required Meta-Agent context file(s): " + ", ".join(missing)
        )

    return "\n---\n\n".join(sections)


def extract_output_text(response: dict[str, Any]) -> str:
    if isinstance(response.get("output_text"), str):
        return response["output_text"].strip()

    parts: list[str] = []
    for item in response.get("output", []):
        for content in item.get("content", []):
            if content.get("type") in {"output_text", "text"} and "text" in content:
                parts.append(str(content["text"]))

    text = "\n".join(parts).strip()
    if not text:
        raise ValueError("OpenAI response did not contain text output.")
    return text


def call_openai(context: str) -> str:
    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        raise RuntimeError("OPENAI_API_KEY is not set. Add it to your environment or .env.")

    model = os.environ.get("OPENAI_MODEL", "gpt-5.2")
    payload = {
        "model": model,
        "instructions": (
            "You are running the ChaOS Meta-Agent review. "
            "Return a Markdown report only. Follow the repository prompt exactly."
        ),
        "input": (
            "Review the following ChaOS repository context using the process "
            "Observe -> Diagnose -> Recommend -> Human Approval.\n\n"
            f"{context}"
        ),
        "max_output_tokens": 4000,
    }

    request = urllib.request.Request(
        "https://api.openai.com/v1/responses",
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )

    try:
        with urllib.request.urlopen(request, timeout=120) as response:
            body = response.read().decode("utf-8")
    except urllib.error.HTTPError as error:
        detail = error.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"OpenAI API request failed: {error.code} {detail}") from error
    except urllib.error.URLError as error:
        raise RuntimeError(f"OpenAI API request failed: {error}") from error

    return extract_output_text(json.loads(body))


def write_report(markdown: str) -> None:
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    header = (
        "<!-- Generated by scripts/run_meta_agent.py. "
        "Recommendations are not applied automatically. -->\n\n"
        f"Generated at: {generated_at}\n\n"
    )
    OUTPUT_PATH.write_text(header + markdown.strip() + "\n", encoding="utf-8")


def main() -> int:
    load_dotenv(ROOT / ".env")
    context = read_context()
    report = call_openai(context)
    write_report(report)
    print(f"Meta-Agent review saved to {OUTPUT_PATH.relative_to(ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as error:
        print(f"Meta-Agent review failed: {error}", file=sys.stderr)
        raise SystemExit(1)

