$ErrorActionPreference = "Stop"

$Root = Resolve-Path (Join-Path $PSScriptRoot "..")
$OutputPath = Join-Path $Root "docs\journal\0001-meta-agent-review.md"
$ContextFiles = @(
    "AGENTS.md",
    "README.md",
    "docs\architecture.md",
    "docs\architectural-laws.md",
    "docs\meta-agent.md",
    "agents\meta-agent\prompt.md"
)

function Import-DotEnv {
    param([string]$Path)

    if (-not (Test-Path -LiteralPath $Path)) {
        return
    }

    Get-Content -LiteralPath $Path | ForEach-Object {
        $Line = $_.Trim()
        if ($Line.Length -eq 0 -or $Line.StartsWith("#") -or -not $Line.Contains("=")) {
            return
        }

        $Parts = $Line.Split("=", 2)
        $Key = $Parts[0].Trim()
        $Value = $Parts[1].Trim().Trim('"').Trim("'")

        if (-not [Environment]::GetEnvironmentVariable($Key, "Process")) {
            [Environment]::SetEnvironmentVariable($Key, $Value, "Process")
        }
    }
}

function Read-ReviewContext {
    $Sections = New-Object System.Collections.Generic.List[string]

    foreach ($RelativePath in $ContextFiles) {
        $FullPath = Join-Path $Root $RelativePath
        if (-not (Test-Path -LiteralPath $FullPath)) {
            throw "Missing required Meta-Agent context file: $RelativePath"
        }

        $Content = (Get-Content -Raw -LiteralPath $FullPath).Trim()
        $NormalizedPath = $RelativePath.Replace("\", "/")
        $Sections.Add("## FILE: $NormalizedPath`n`n$Content`n")
    }

    return ($Sections -join "`n---`n`n")
}

function Get-ResponseText {
    param($Response)

    if ($Response.output_text) {
        return [string]$Response.output_text
    }

    $Parts = New-Object System.Collections.Generic.List[string]
    foreach ($Item in $Response.output) {
        foreach ($Content in $Item.content) {
            if (($Content.type -eq "output_text" -or $Content.type -eq "text") -and $Content.text) {
                $Parts.Add([string]$Content.text)
            }
        }
    }

    $Text = ($Parts -join "`n").Trim()
    if (-not $Text) {
        throw "OpenAI response did not contain text output."
    }
    return $Text
}

function Invoke-MetaAgent {
    param([string]$Context)

    $ApiKey = [Environment]::GetEnvironmentVariable("OPENAI_API_KEY", "Process")
    if (-not $ApiKey) {
        throw "OPENAI_API_KEY is not set. Add it to your environment or .env."
    }

    $Model = [Environment]::GetEnvironmentVariable("OPENAI_MODEL", "Process")
    if (-not $Model) {
        $Model = "gpt-5.2"
    }

    $Body = @{
        model = $Model
        instructions = "You are running the ChaOS Meta-Agent review. Return a Markdown report only. Follow the repository prompt exactly."
        input = "Review the following ChaOS repository context using the process Observe -> Diagnose -> Recommend -> Human Approval.`n`n$Context"
        max_output_tokens = 4000
    } | ConvertTo-Json -Depth 8

    $Headers = @{
        Authorization = "Bearer $ApiKey"
        "Content-Type" = "application/json"
    }

    $Response = Invoke-RestMethod `
        -Uri "https://api.openai.com/v1/responses" `
        -Method Post `
        -Headers $Headers `
        -Body $Body

    return Get-ResponseText -Response $Response
}

Import-DotEnv -Path (Join-Path $Root ".env")
$Context = Read-ReviewContext
$Report = Invoke-MetaAgent -Context $Context

$OutputDirectory = Split-Path -Parent $OutputPath
New-Item -ItemType Directory -Force -Path $OutputDirectory | Out-Null

$GeneratedAt = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
$Header = "<!-- Generated by scripts/run_meta_agent.ps1. Recommendations are not applied automatically. -->`n`nGenerated at: $GeneratedAt`n`n"
Set-Content -LiteralPath $OutputPath -Value ($Header + $Report.Trim() + "`n") -Encoding UTF8

$RelativeOutput = "docs/journal/0001-meta-agent-review.md"
Write-Host "Meta-Agent review saved to $RelativeOutput"

